#
# Copyright (C) 2022 Ing <https://github.com/wjz304>
#
# This is free software, licensed under the MIT License.
# See /LICENSE for more information.
#

name: Build OpenCore-Mod

on:
  push:
  schedule:
    - cron: "20 */6 * * *"
  workflow_dispatch:

env:
  PROJECT_TYPE: UEFI
  FORCE_INSTALL: 1
  HAS_OPENSSL_BUILD: 1
  HAS_OPENSSL_W32BUILD: 0
  WERROR: 1

jobs:
  build-macos:
    name: macOS XCODE5
    runs-on: macos-14
    env:
      JOB_TYPE: BUILD
      HOMEBREW_NO_INSTALL_CLEANUP: 1
      HOMEBREW_NO_AUTO_UPDATE: 1
    steps:
      - name: Checkout
        uses: actions/checkout@main

      - name: Initialization environment
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          sudo systemsetup -settimezone "Asia/Shanghai"

      - name: Install Linux Toolchain
        run: |
          brew tap FiloSottile/homebrew-musl-cross
          brew install musl-cross
          brew install openssl mingw-w64 nasm jq

      - name: CI Bootstrap
        run: |
          git clone https://github.com/acidanthera/OpenCorePkg.git OpenCore_Mod
          cd ./OpenCore_Mod

          src=$(/usr/bin/curl -LfsS https://raw.githubusercontent.com/acidanthera/ocbuild/master/ci-bootstrap.sh) && eval "$src" || exit 1

          # jq parses json, # token https://docs.github.com/en/developers/apps/building-oauth-apps/authorizing-oauth-apps  
          latesttag=$(curl -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" -sL https://api.github.com/repos/${GITHUB_REPOSITORY}/releases/latest | jq -r .tag_name)
          latestgit=${latesttag#*_}
          currenttag=$(grep OPEN_CORE_VERSION Include/Acidanthera/Library/OcMainLib.h | sed 's/.*"\(.*\)".*/\1/' | grep -E '^[0-9.]+$')_$(git rev-parse --short HEAD)
          currentgit=${currenttag#*_}

          echo latesttag: $latesttag
          echo latestgit: $latestgit
          echo currenttag: $currenttag
          echo currentgit: $currentgit

          if [ "${latesttag}" == "${currenttag}" ]; then
            echo "isNew=false" >> $GITHUB_ENV
          else
            # git diff > mod.patch
            if git apply --check $GITHUB_WORKSPACE/mod.patch; then
              git apply $GITHUB_WORKSPACE/mod.patch
              curhead=${currentgit}
              curdate=$(date +"%Y-%m-%d")
              curuser=304403268
              sed -i'.bak' "s/OpenCore-Mod-XXXXXXXX-XXXX-XX-XX-XXXXXXXXXX/OpenCore-Mod-${curhead}-${curdate}-${curuser}/" ./Library/OcMainLib/OpenCoreMisc.c
              echo "isNew=true" >> $GITHUB_ENV
              echo "currenttag=${currenttag}" >> $GITHUB_ENV
              echo "gitrevhead=${currentgit}" >> $GITHUB_ENV
              [ "${latestgit}" == "null" ] && latestgit=.
              echo 'gitupgrade<<EOF' >> $GITHUB_ENV
              git log ${latestgit}..${currentgit} --oneline >> $GITHUB_ENV
              echo 'EOF' >> $GITHUB_ENV
            else
              echo "isNew=false" >> $GITHUB_ENV
              echo "patch error"
              exit 1
            fi
          fi

      - name: build Duet
        if: env.isNew == 'true'
        run: cd OpenCore_Mod && ./build_duet.tool

      - name: build OC
        if: env.isNew == 'true'
        run: cd OpenCore_Mod && ./build_oc.tool

      - name: Upload to Artifacts
        if: env.isNew == 'true'
        uses: actions/upload-artifact@v4
        with:
          name: macOS XCODE5 Artifacts
          path: OpenCore_Mod/Binaries/*.zip

      - name: Commit and Push
        if: env.isNew == 'true'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}        
        run: |
          echo ${{ env.currenttag }} > latest
          git add latest
          git commit -m "update $(date +%Y-%m-%d" "%H:%M:%S)"
          git push -f

      - name: Upload to Release
        if: env.isNew == 'true'
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ env.currenttag }}
          body: |
            Changes:  
            ${{ env.gitupgrade }}  
            [View on OpenCorePkg](https://github.com/acidanthera/OpenCorePkg/commits/master)
          files: OpenCore_Mod/Binaries/*.zip
